### PR TITLE
Yojahuang hw4 attempt1

### PR DESCRIPTION
**Pull request by Yojahuang**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Review by yungyuc — CHANGES_REQUESTED** [review]
Please do not merge against `master` branch

**Comment by Yojahuang** [comment]
Updated

**Comment by yungyuc** [comment]
No problem. What kind of drink it was?

**Review by yungyuc — APPROVED** [review]

**Comment by season06** [comment]
CI didn't run, could you fix it?

**Comment by yungyuc** [comment]
@Yojahuang Perhaps you can try to make a forced rebase or squash.

**Comment by Yojahuang** [comment]
Fixed!

**Comment by Yojahuang** [comment]
@yungyuc i think the reason of CI didn't run is because I selected wrong target branch at the first place, but I got deduct for 3 points in this HW, is it possible that I can get my points back 👏?

**Comment by season06** [comment]
sure, I will update the grade.

**Comment by Yojahuang** [comment]
Thanks a lot!

**Pull request merged**
