### PR TITLE
jamie212 hw2 attempt1

### PR DESCRIPTION
**Pull request by jamie212**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by jamie212** [comment]
Hello, Professor @yungyuc . May I ask if there is anything wrong with my submission? I noticed that it was not tagged for hw2.

**Comment by yungyuc** [comment]
> Hello, Professor @yungyuc . May I ask if there is anything wrong with my submission? I noticed that it was not tagged for hw2.

I simply didn't have time to tag.  Tagging doesn't mean review, just to help grade and me track the PRs.

**Comment by jamie212** [comment]
> > Hello, Professor @yungyuc . May I ask if there is anything wrong with my submission? I noticed that it was not tagged for hw2.
> 
> I simply didn't have time to label. Labeling doesn't mean review, just to help grade and me track the PRs.
> 
> Should you have any questions, feel free to contact the grader for help.

Okay, I understand. I'm sorry to bother you, and thank you for your response.

**Comment by yungyuc** [comment]
> > > Hello, Professor @yungyuc . May I ask if there is anything wrong with my submission? I noticed that it was not tagged for hw2.
> > 
> > 
> > I simply didn't have time to label. Labeling doesn't mean review, just to help grade and me track the PRs.
> > Should you have any questions, feel free to contact the grader for help.
> 
> Okay, I understand. I'm sorry to bother you, and thank you for your response.

Keep bothering me.

**Pull request merged**
